export const FRONTEGG_STORE_KEY = 'FRONTEGG_STORE_KEY';
export const FRONTEGG_ACTIONS_KEY = 'FRONTEGG_ACTIONS_KEY';
export const FRONTEGG_REDUX_BINDINGS = 'FRONTEGG_REDUX_BINDINGS';
export const FRONTEGG_UNSUBSCRIBE = 'FRONTEGG_UNSUBSCRIBE';
export const FRONTEGG_LOADER_UNSUBSCRIBE = 'FRONTEGG_LOADER_UNSUBSCRIBE';
