name: Push Workflow
on:
  # When after commit pushed to branches not master nad release/next
  push:
    branches-ignore:
      - 'master'
      - 'release/next'
env:
  CI: true
jobs:
  init:
    name: 'Install, Build and Test'
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.13.0-chrome80-ff74
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: make clean
      - run: make install
      - name: "Set Generated changelog"
        uses: actions/github-script@v6
        id: 'generated-changelog'
        with:
          result-encoding: string
          script: |
            const fs = await import('fs')
            console.log(context);
            console.log(github.workspace);
            console.log(process.env);
            console.log(fs.readdirSync(`${{ github.workspace }}/.github/scripts`));
            const { generateChangeLog } = await import(`${{ github.workspace }}/.github/scripts/index.js`);
            return generateChangeLog({context, github, core})
      - run: make build
